---
abstract: 'Dist::Zilla plugin bundle for PadrePlugin'
author:
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-PadrePlugin
requires:
  Dist::Zilla: 0
  Dist::Zilla::Plugin::CheckChangeLog: 0
  Dist::Zilla::Plugin::CheckChangesTests: 0
  Dist::Zilla::Plugin::CompileTests: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::LocaleMsgfmt: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaResources: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Moose::Autobox: 0
resources:
  homepage: http://padre.perlide.org
  repository: http://svn.perlide.org/padre/trunk/Dist-Zilla-PluginBundle-PadrePlugin/
version: 0.08
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Basic/GatherDir'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Basic/PruneCruft'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Basic/ManifestSkip'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Basic/MetaYAML'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::License
      name: '@Basic/License'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Basic/Readme'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Basic/ExtraTests'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Basic/ExecDir'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Basic/ShareDir'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Basic/MakeMaker'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Basic/Manifest'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Basic/TestRelease'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Basic/ConfirmRelease'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Basic/UploadToCPAN'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::CheckChangesTests
      name: CheckChangesTests
      version: 1.100900
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: CompileTests
      version: 1.103030
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: EOLTests
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102345
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102345
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102345
